import "./globals.css";
import Header from "@/Components/Header";
import MyContext from "@/Helper/Context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" suppressHydrationWarning>
        <Header logo={"LOGO"} />
     
        <MyContext>{children}</MyContext>

      </body>
    </html>
  );
}
